a=1
print(a)
b='kp'
print(b)
c=True
print(c)
d=None
print(d)
e=complex(8,2)
print(e)
list1=[0,1,2,[-4,5],["apple","banana"]]
print(list1)
tuple1=(("kp","pk"),("java","php"))
print(tuple1)
dict1={"name":"Kip","age":21,"canVote":True}
print(dict1)
print("\n")
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(list1))
print(type(tuple1))
print(type(dict1))